config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'statics#home'
  get '/about', to: 'statics#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="footer-inner bg-dark">
    <h2 class="text-light text-center">beautiful scenery</h2>
    <nav class="d-flex justify-content-center navbar-dark">
      <ul class="navbar-nav flex-row">
        <li class="nav-item">
          <%= link_to "お問い合わせ", "#", class:"nav-link font-italic px-5" %>
        </li>
        <li class="nav-item">
          <%= link_to "お問い合わせ", "#", class:"nav-link font-italic px-5" %>
        </li>
        <li class="nav-item">
          <%= link_to "お問い合わせ", "#", class:"nav-link font-italic px-5" %>
        </li>
        <li class="nav-item">
          <%= link_to "お問い合わせ", "#", class:"nav-link font-italic px-5" %>
        </li>
      </ul>
    </nav>
    <p class="text-light text-center p-4 m-0">COPYRIGHT © beautiful scenery ALL RIGHTS RESERVED.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header id="header">
  <div class="header-inner">
    <nav class="d-flex justify-content-center navbar-dark bg-dark px-5 py-2">
      <ul class="left-side-navs navbar-nav flex-row justify-content-end">
        <li class="nav-item align-self-center">
          <%= link_to "HOME", home_path, class:"nav-link font-italic sm-navs pr-5" %>
        </li>
        <li class="nav-item align-self-center">
          <%= link_to "ABOUT", about_path, class:"nav-link font-italic sm-navs px-4" %>
        </li>
      </ul>
      <div class="center-nav">
        <%= link_to "Beautiful Scenery", home_path, class:"nav-link text-light font-italic navbar-brand logo mx-5 px-5" %>
      </div>
      <ul class="right-side-navs navbar-nav flex-row">
         <li class="nav-item px-4 align-self-center">
          <%= link_to "SIGN UP", "#", class:"nav-link font-italic sm-navs" %>
        </li>
        <li class="nav-item px-4 align-self-center">
          <%= link_to "LOG IN", "#", class:"nav-link font-italic sm-navs" %>
        </li>
      </ul>
    </nav>
    <nav class="search-nav navbar navbar-light bg-light">
      <form class="form-inline">
        <input class="form-control mer-sm-2" type="text" placeholder="Search">
        <button class="btn btn-outline-success my-2 my-sm-0 mx-2" type="submit">Search</button>
      </form>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeautifulScenery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/statics/about.html.erb
<main id="main" class="main bg-light">
  <div class="top-wrapper">
    <div class="dark-pic">
      <h2 class="text-center">
        FIND YOUR SCENERY
        <br>
        IT STILL HIDE
      </h2>
    </div>
  </div>
  <div class="d-flex row">
    <section class="main-section ml-5 mt-md-5">
      <div class="intro">
        <h3 class="text-center p-3">About Beautiful Scenery</h3>
        <div class="about d-flex">
          <p>
            We introduce many beautiful sceneries in japan. You can find out what you want to see with this app and rate places you will go after you have amazing feeling with sceneries.
            <br>
            this is dummy text
            <br>
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.
          </p>
          <%= image_tag "2.jpg", alt:"scenery", class:"recommended-img mb-3 d-block", width: "260px" %>
        </div>
        <h3 class="text-center p-3 mt-md-5">How to Use</h3>
        <div class="how-to-use d-flex">
          <%= image_tag "2.jpg", alt:"scenery", class:"recommended-img mr-3 mb-3 d-block", width: "260px" %>
          <p>
            We introduce many beautiful sceneries in japan. You can find out what you want to see with this app and rate places you will go after you have amazing feeling with sceneries.
            <br>
            this is dummy text
            <br>
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.
          </p>
        </div>
      </div>
    </section>
    <aside class="aside ml-md-5 mt-md-5 pt-md-4">
      <div class="ads">
        <%= image_tag "1.png", alt:"ad", class:"d-block bg-dark mb-md-4", width: "400px" %>
        <%= image_tag "1.png", alt:"ad", class:"d-block bg-dark mb-md-4", width: "400px" %>
        <%= image_tag "1.png", alt:"ad", class:"d-block bg-dark mb-md-4", width: "400px" %>
      </div>
    </aside>
  </div>
</main>

app/views/statics/home.html.erb
<main id="main" class="main bg-light">
  <div class="top-wrapper">
    <div class="animated-pics">
      <%= image_tag "1.jpg", alt:"scenery", class:"img img1", width: "100%" %>
      <%= image_tag "2.jpg", alt:"scenery", class:"img img2", width: "100%" %>
      <%= image_tag "3.jpg", alt:"scenery", class:"img img3", width: "100%" %>
      <%= image_tag "4.jpg", alt:"scenery", class:"img img4", width: "100%" %>
    </div>
  </div>
  <div class="d-flex row">
    <section class="ml-5">
      <h2 class="text-center p-3">These places will take your breath away</h2>
      <div class="recommended-pic ml-5">
        <a class="card1" href="#">
          <%= image_tag "1.jpg", alt:"scenery", class:"recommended-img mx-auto mb-3 d-block", width: "260px" %>
          <p class="m-1">place</p>
          <p class="m-1">this is a famous scenery in japan.</p>
        </a>
        <a class="card2" href="#">
          <%= image_tag "2.jpg", alt:"scenery", class:"recommended-img mx-auto mb-3 d-block", width: "260px" %>
          <p class="m-1">place</p>
          <p class="m-1">this is a famous scenery in japan.</p>
        </a>
        <a class="card3" href="#">
          <%= image_tag "3.jpg", alt:"scenery", class:"recommended-img mx-auto mb-3 d-block", width: "260px" %>
          <p class="m-1">place</p>
          <p class="m-1">this is a famous scenery in japan.</p>
        </a>
        <a class="card4" href="#">
          <%= image_tag "4.jpg", alt:"scenery", class:"recommended-img mx-auto mb-3 d-block", width: "260px" %>
          <p class="m-1">place</p>
          <p class="m-1">this is a famous scenery in japan.</p>
        </a>
        <a class="card5" href="#">
          <%= image_tag "1.jpg", alt:"scenery", class:"recommended-img mx-auto mb-3 d-block", width: "260px" %>
          <p class="m-1">place</p>
          <p class="m-1">this is a famous scenery in japan.</p>
        </a>
        <a class="card6" href="#">
          <%= image_tag "2.jpg", alt:"scenery", class:"recommended-img mx-auto mb-3 d-block", width: "260px" %>
          <p class="m-1">place</p>
          <p class="m-1">this is a famous scenery in japan.</p>
        </a>
      </div>
    </section>
    <aside class="aside ml-md-5 mt-md-5 pt-md-4">
      <div class="ads">
        <%= image_tag "1.png", alt:"ad", class:"d-block bg-dark mb-md-4", width: "400px" %>
        <%= image_tag "1.png", alt:"ad", class:"d-block bg-dark mb-md-4", width: "400px" %>
        <%= image_tag "1.png", alt:"ad", class:"d-block bg-dark mb-md-4", width: "400px" %>
      </div>
    </aside>
  </div>
</main>